### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by websecer** [teamssix/cf#206]
### 描述你遇到的问题 (What happened?)

`panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x1ef49ee]

goroutine 1 [running]:
github.com/teamssix/cf/pkg/cloud/tencent/tencentconsole.GetUserUin({0x23ac17d, 0x9})
        /home/runner/work/cf/cf/pkg/cloud/tencent/tencentconsole/takeoverConsole.go:42 +0x30e
github.com/teamssix/cf/pkg/cloud/tencent/tencentconsole.AttachPolicyToUser({0x23ac17d, 0x9})
        /home/runner/work/cf/cf/pkg/cloud/tencent/tencentconsole/takeoverConsole.go:46 +0x3b
github.com/teamssix/cf/pkg/cloud/tencent/tencentconsole.TakeoverConsole({0x23ac17d, 0x9})
        /home/runner/work/cf/cf/pkg/cloud/tencent/tencentconsole/takeoverConsole.go:68 +0x7a
github.com/teamssix/cf/cmd/tencent.glob..func1(0x3af63a0?, {0x23a8099?, 0x0?, 0x0?})
        /home/runner/work/cf/cf/cmd/tencent/console.go:27 +0x27
github.com/spf13/cobra.(*Command).execute(0x3af63a0, {0x3b57c50, 0x0, 0x0})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:876 +0x67b
github.com/spf13/cobra.(*Command).ExecuteC(0x3af13a0)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918
github.com/teamssix/cf/cmd.Execute()
        /home/runner/work/cf/cf/cmd/root.go:50 +0x55
main.main()
        /home/runner/work/cf/cf/main.go:12 +0x17
`

### 复现步骤 (Steps To Reproduce)

 cf tencent console

### 操作系统 (Operating System)

win10

### 系统类型 (System Type)

amd64

### CF 版本 ( CF Version)

最新的 (Latest)

**Comment by teamssix** [comment]
可以执行一下这个命令：`cf tencent console --logLevel trace` ，看看有没有什么报错，我这边这个功能是正常的

**Comment by teamssix** [comment]
这个 issue 在 30 天内没有任何活动，如果在 7 天后依然没有任何动静，那么这个 issue 将会自动关闭。(This issue is stale because it has been open for 30 days with no activity.)

**Comment by teamssix** [comment]
这个 issue 由于长时间没有动静，已自动关闭。(This issue was closed because it has been inactive for 7 days since being marked as stale.)
