### ISSUE TITLE
huawei cloud error

### ISSUE THREAD

**Issue by websecer** [teamssix/cf#210]
### 描述你遇到的问题 (What happened?)

`[2023-02-14 03:07:40] ERROR XML syntax error on line 1: illegal character code U+0015
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x50 pc=0x1426a2a]

goroutine 1 [running]:
github.com/teamssix/cf/pkg/cloud/huawei/huaweiobs.ListObjects({0xc0003e4610, 0xd}, {0xc0003e4375, 0x9}, {0x1916d14, 0x3}, {0xc000f9a1e0,
 0x60})
        /home/runner/work/cf/cf/pkg/cloud/huawei/huaweiobs/obslsobject.go:51 +0x24a
github.com/teamssix/cf/pkg/cloud/huawei/huaweiobs.ListObjects({0xc0003e4610, 0xd}, {0xc0003e4375, 0x9}, {0x1916d14, 0x3}, {0xc000d3e1e0,
 0x5b})
        /home/runner/work/cf/cf/pkg/cloud/huawei/huaweiobs/obslsobject.go:84 +0x585
github.com/teamssix/cf/pkg/cloud/huawei/huaweiobs.ListObjects({0xc0003e4610, 0xd}, {0xc0003e4375, 0x9}, {0x1916d14, 0x3}, {0xc000d2a060,
 0x55})
        /home/runner/work/cf/cf/pkg/cloud/huawei/huaweiobs/obslsobject.go:84 +0x585
github.com/teamssix/cf/pkg/cloud/huawei/huaweiobs.ListObjects({0xc0003e4610, 0xd}, {0xc0003e4375, 0x9}, {0x1916d14, 0x3}, {0xc00084c180,
 0x73})
        /home/runner/work/cf/cf/pkg/cloud/huawei/huaweiobs/obslsobject.go:84 +0x585
github.com/teamssix/cf/pkg/cloud/huawei/huaweiobs.ListObjects({0xc0003e4610, 0xd}, {0xc0003e4375, 0x9}, {0x1916d14, 0x3}, {0xc000f30900,
 0x5c})
        /home/runner/work/cf/cf/pkg/cloud/huawei/huaweiobs/obslsobject.go:84 +0x585
github.com/teamssix/cf/pkg/cloud/huawei/huaweiobs.ListObjects({0xc0003e4610, 0xd}, {0xc0003e4375, 0x9}, {0x1916d14, 0x3}, {0xc0006d4d80,
 0x7a})
        /home/runner/work/cf/cf/pkg/cloud/huawei/huaweiobs/obslsobject.go:84 +0x585
github.com/teamssix/cf/pkg/cloud/huawei/huaweiobs.ListObjects({0xc0003e4610, 0xd}, {0xc0003e4375, 0x9}, {0x1916d14, 0x3}, {0xc00075e000,
 0x6b})
        /home/runner/work/cf/cf/pkg/cloud/huawei/huaweiobs/obslsobject.go:84 +0x585
github.com/teamssix/cf/pkg/cloud/huawei/huaweiobs.ListObjects({0xc0003e4610, 0xd}, {0xc0003e4375, 0x9}, {0x1916d14, 0x3}, {0xc0007af1a0,
 0x5e})
        /home/runner/work/cf/cf/pkg/cloud/huawei/huaweiobs/obslsobject.go:84 +0x585
github.com/teamssix/cf/pkg/cloud/huawei/huaweiobs.ListObjects({0xc0003e4610, 0xd}, {0xc0003e4375, 0x9}, {0x1916d14, 0x3}, {0xc000ca65a0,
 0x55})
        /home/runner/work/cf/cf/pkg/cloud/huawei/huaweiobs/obslsobject.go:84 +0x585
github.com/teamssix/cf/pkg/cloud/huawei/huaweiobs.ListObjects({0xc0003e4610, 0xd}, {0xc0003e4375, 0x9}, {0x1916d14, 0x3}, {0xc00064a5f0,
 0x4d})
        /home/runner/work/cf/cf/pkg/cloud/huawei/huaweiobs/obslsobject.go:84 +0x585
github.com/teamssix/cf/pkg/cloud/huawei/huaweiobs.ListObjects({0xc0003e4610, 0xd}, {0xc0003e4375, 0x9}, {0x1916d14, 0x3}, {0xc000cca720,
 0x59})
        /home/runner/work/cf/cf/pkg/cloud/huawei/huaweiobs/obslsobject.go:84 +0x585
github.com/teamssix/cf/pkg/cloud/huawei/huaweiobs.ListObjects({0xc0003e4610, 0xd}, {0xc0003e4375, 0x9}, {0x1916d14, 0x3}, {0xc00082a360,
 0x5c})
        /home/runner/work/cf/cf/pkg/cloud/huawei/huaweiobs/obslsobject.go:84 +0x585
github.com/teamssix/cf/pkg/cloud/huawei/huaweiobs.ListObjects({0xc0003e4610, 0xd}, {0xc0003e4375, 0x9}, {0x1916d14, 0x3}, {0xc00091be30,
 0x6d})
        /home/runner/work/cf/cf/pkg/cloud/huawei/huaweiobs/obslsobject.go:84 +0x585
github.com/teamssix/cf/pkg/cloud/huawei/huaweiobs.ListObjects({0xc0003e4610, 0xd}, {0xc0003e4375, 0x9}, {0x1916d14, 0x3}, {0xc0006e2600,
 0x5b})
        /home/runner/work/cf/cf/pkg/cloud/huawei/huaweiobs/obslsobject.go:84 +0x585
github.com/teamssix/cf/pkg/cloud/huawei/huaweiobs.ListObjects({0xc0003e4610, 0xd}, {0xc0003e4375, 0x9}, {0x1916d14, 0x3}, {0xc00072c1e0,
 0x59})
        /home/runner/work/cf/cf/pkg/cloud/huawei/huaweiobs/obslsobject.go:84 +0x585
github.com/teamssix/cf/pkg/cloud/huawei/huaweiobs.ListObjects({0xc0003e4610, 0xd}, {0xc0003e4375, 0x9}, {0x1916d14, 0x3}, {0xc0006540e0,
 0x64})
        /home/runner/work/cf/cf/pkg/cloud/huawei/huaweiobs/obslsobject.go:84 +0x585
github.com/teamssix/cf/pkg/cloud/huawei/huaweiobs.ListObjects({0xc0003e4610, 0xd}, {0xc0003e4375, 0x9}, {0x1916d14, 0x3}, {0xc0006b3260,
 0x55})
        /home/runner/work/cf/cf/pkg/cloud/huawei/huaweiobs/obslsobject.go:84 +0x585
github.com/teamssix/cf/pkg/cloud/huawei/huaweiobs.ListObjects({0xc0003e4610, 0xd}, {0xc0003e4375, 0x9}, {0x1916d14, 0x3}, {0x0, 0x0})
        /home/runner/work/cf/cf/pkg/cloud/huawei/huaweiobs/obslsobject.go:84 +0x585
github.com/teamssix/cf/pkg/cloud/huawei/huaweiobs.getBucketObjectSum({0xc0003e4610, 0xd}, {0xc0003e4375, 0x9}, {0x1916d14, 0x3})
        /home/runner/work/cf/cf/pkg/cloud/huawei/huaweiobs/obsls.go:104 +0xf6
github.com/teamssix/cf/pkg/cloud/huawei/huaweiobs.PrintBucketsListRealTime({0x1916d14, 0x3}, {0x1916d14, 0x3})
        /home/runner/work/cf/cf/pkg/cloud/huawei/huaweiobs/obsls.go:132 +0x417
github.com/teamssix/cf/pkg/cloud/huawei/huaweiobs.PrintBucketsList({0x1916d14, 0x3}, 0x93?, {0x1916d14, 0x3})
        /home/runner/work/cf/cf/pkg/cloud/huawei/huaweiobs/obsls.go:158 +0x8a
github.com/teamssix/cf/cmd/huawei.glob..func1(0x3066120?, {0x1918099?, 0x0?, 0x0?})
        /home/runner/work/cf/cf/cmd/huawei/obs.go:37 +0xbe
github.com/spf13/cobra.(*Command).execute(0x3066120, {0x30c7c50, 0x0, 0x0})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:876 +0x67b
github.com/spf13/cobra.(*Command).ExecuteC(0x30613a0)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918
github.com/teamssix/cf/cmd.Execute()
        /home/runner/work/cf/cf/cmd/root.go:50 +0x55
main.main()
        /home/runner/work/cf/cf/main.go:12 +0x17`

### 复现步骤 (Steps To Reproduce)

cf huawei obs ls

### 操作系统 (Operating System)

Windows

### 系统类型 (System Type)

amd64

### CF 版本 ( CF Version)

最新的 (Latest)

**Comment by teamssix** [comment]
这个 issue 在 60 天内没有任何活动，如果在 30 天后依然没有任何动静，那么这个 issue 将会自动关闭。(This issue is stale because it has been open for 60 days with no activity.)

**Comment by teamssix** [comment]
本地无法复现这个问题，可以加上 --logLevel trace 看看有没有什么报错

**Comment by teamssix** [comment]
由于长时间未回复，将关闭此 Issue
